# Copyright IBM Corp. 2024, 2026
# SPDX-License-Identifier: BUSL-1.1

services:
  dev-portal:
    image: 'hashicorp/dev-portal:latest'
    container_name: dev-portal
    ports:
      - ${DEV_PORTAL_PORT}:${DEV_PORTAL_PORT}
    depends_on:
      unified-docs-api:
        condition: service_healthy
    environment:
      - MKTG_CONTENT_DOCS_API=https://content.hashicorp.com
      - UNIFIED_DOCS_PORT=${UNIFIED_DOCS_PORT}
      - UNIFIED_DOCS_API=http://unified-docs-api:${UNIFIED_DOCS_PORT}
      - HASHI_ENV=unified-docs-sandbox
      - NODE_ENV=development
    profiles: [unified-docs]

  unified-docs-api:
    build: .
    container_name: unified-docs-api
    ports:
      - ${UNIFIED_DOCS_PORT}:${UNIFIED_DOCS_PORT}
    environment:
      - DEV_PORTAL_URL=http://dev-portal:${DEV_PORTAL_PORT}
    volumes:
      - ./content:/server/content
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${UNIFIED_DOCS_PORT}"]
      interval: 90s
      timeout: 10s
      retries: 5
      start_period: 120s
